import type {
  MessageTemplate,
  MiniProgramPageMeta,
  OrderNodeDefinition,
  RolePermissionMatrix,
} from './types'

export const MINI_PROGRAM_PAGES: MiniProgramPageMeta[] = [
  {
    id: 'user-home',
    name: '用户首页',
    path: '/mp/user/home',
    portal: 'user',
    description: '快捷发布需求、查看附近服务商推荐、活动Banner',
    requiresAuth: true,
    allowedRoles: ['user'],
  },
  {
    id: 'user-publish',
    name: '发布需求',
    path: '/mp/user/publish',
    portal: 'user',
    description: '填写吊装需求、自动/手动距离修正、提交订单',
    requiresAuth: true,
    allowedRoles: ['user'],
  },
  {
    id: 'user-orders',
    name: '用户订单中心',
    path: '/mp/user/orders',
    portal: 'user',
    description: '订单列表、状态筛选、节点进度查看',
    requiresAuth: true,
    allowedRoles: ['user'],
  },
  {
    id: 'user-order-detail',
    name: '用户订单详情',
    path: '/mp/user/orders/:orderId',
    portal: 'user',
    description: '10节点时间线、确认报价/拒绝报价、评价、投诉入口',
    requiresAuth: true,
    allowedRoles: ['user'],
  },
  {
    id: 'user-messages',
    name: '用户消息中心',
    path: '/mp/user/messages',
    portal: 'user',
    description: '站内信、订阅消息触达记录',
    requiresAuth: true,
    allowedRoles: ['user'],
  },
  {
    id: 'provider-dashboard',
    name: '服务商工作台',
    path: '/mp/provider/dashboard',
    portal: 'provider',
    description: '订单概览、待办提醒、快捷操作',
    requiresAuth: true,
    allowedRoles: ['provider_admin', 'customer_service', 'ground_crew', 'pilot', 'finance'],
  },
  {
    id: 'provider-orders',
    name: '服务商订单列表',
    path: '/mp/provider/orders',
    portal: 'provider',
    description: '按状态/节点筛选订单，进入节点操作',
    requiresAuth: true,
    allowedRoles: ['provider_admin', 'customer_service', 'ground_crew', 'pilot', 'finance'],
  },
  {
    id: 'provider-order-detail',
    name: '服务商订单详情',
    path: '/mp/provider/orders/:orderId',
    portal: 'provider',
    description: '按角色执行节点操作，上传凭证与记录',
    requiresAuth: true,
    allowedRoles: ['provider_admin', 'customer_service', 'ground_crew', 'pilot', 'finance'],
  },
  {
    id: 'provider-tasks',
    name: '我的任务',
    path: '/mp/provider/tasks',
    portal: 'provider',
    description: '地勤/飞手任务视图，快速执行前往/开始/结束节点',
    requiresAuth: true,
    allowedRoles: ['ground_crew', 'pilot'],
  },
  {
    id: 'provider-finance',
    name: '财务处理',
    path: '/mp/provider/finance',
    portal: 'provider',
    description: '开具发票、标记收款、查看待收款',
    requiresAuth: true,
    allowedRoles: ['provider_admin', 'finance'],
  },
]

export const ORDER_NODE_FLOW: OrderNodeDefinition[] = [
  {
    code: 'SUBMIT_DEMAND',
    label: '提交需求',
    operatorRoles: ['user'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'PROVIDER_ACCEPT',
    label: '服务商接单',
    operatorRoles: ['provider_admin', 'customer_service'],
    userVisible: true,
    providerVisible: true,
    timeoutHours: 2,
    autoCloseOnTimeout: true,
  },
  {
    code: 'PROVIDER_QUOTE',
    label: '服务商报价',
    operatorRoles: ['provider_admin', 'customer_service'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'USER_CONFIRM_QUOTE',
    label: '用户确认报价',
    operatorRoles: ['user'],
    userVisible: true,
    providerVisible: true,
    timeoutHours: 24,
    autoCloseOnTimeout: true,
  },
  {
    code: 'RESOURCE_ASSIGN',
    label: '资源分配',
    operatorRoles: ['provider_admin', 'customer_service'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'DEPART_TO_SITE',
    label: '前往吊运地点',
    operatorRoles: ['ground_crew', 'provider_admin'],
    userVisible: true,
    providerVisible: true,
    timeoutHours: 1,
  },
  {
    code: 'START_LIFTING',
    label: '开始吊运',
    operatorRoles: ['pilot', 'provider_admin'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'FINISH_LIFTING',
    label: '吊运结束',
    operatorRoles: ['pilot', 'provider_admin'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'ISSUE_INVOICE',
    label: '开具发票',
    operatorRoles: ['finance', 'provider_admin'],
    userVisible: true,
    providerVisible: true,
  },
  {
    code: 'USER_REVIEW',
    label: '评价服务',
    operatorRoles: ['user'],
    userVisible: true,
    providerVisible: true,
  },
]

export const ROLE_PERMISSION_MATRIX: RolePermissionMatrix[] = [
  {
    role: 'user',
    visibleMenus: ['home', 'publish', 'orders', 'messages', 'profile', 'complaints'],
    allowedNodeActions: ['SUBMIT_DEMAND', 'USER_CONFIRM_QUOTE', 'USER_REVIEW'],
  },
  {
    role: 'provider_admin',
    visibleMenus: ['dashboard', 'orders', 'tasks', 'finance'],
    allowedNodeActions: [
      'PROVIDER_ACCEPT',
      'PROVIDER_QUOTE',
      'RESOURCE_ASSIGN',
      'DEPART_TO_SITE',
      'START_LIFTING',
      'FINISH_LIFTING',
      'ISSUE_INVOICE',
    ],
  },
  {
    role: 'customer_service',
    visibleMenus: ['dashboard', 'orders'],
    allowedNodeActions: ['PROVIDER_ACCEPT', 'PROVIDER_QUOTE', 'RESOURCE_ASSIGN'],
  },
  {
    role: 'ground_crew',
    visibleMenus: ['orders', 'tasks'],
    allowedNodeActions: ['DEPART_TO_SITE'],
  },
  {
    role: 'pilot',
    visibleMenus: ['orders', 'tasks'],
    allowedNodeActions: ['START_LIFTING', 'FINISH_LIFTING'],
  },
  {
    role: 'finance',
    visibleMenus: ['orders', 'finance'],
    allowedNodeActions: ['ISSUE_INVOICE'],
  },
]

export const MESSAGE_TEMPLATES: MessageTemplate[] = [
  {
    key: 'demand_submitted',
    triggerNode: 'SUBMIT_DEMAND',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '您的吊装需求已提交，订单号{{orderId}}，等待服务商接单。',
  },
  {
    key: 'provider_quoted',
    triggerNode: 'PROVIDER_QUOTE',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '服务商已报价 {{amount}} 元，请及时确认。',
  },
  {
    key: 'user_confirmed_quote',
    triggerNode: 'USER_CONFIRM_QUOTE',
    recipient: 'provider',
    channels: ['in_app'],
    content: '用户已确认报价，请尽快分配飞手与地勤。',
  },
  {
    key: 'depart_to_site',
    triggerNode: 'DEPART_TO_SITE',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '地勤/飞手已出发前往吊运地点，请保持电话畅通。',
  },
  {
    key: 'start_lifting',
    triggerNode: 'START_LIFTING',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '飞手已开始吊运，可在订单详情中查看进度。',
  },
  {
    key: 'finish_lifting',
    triggerNode: 'FINISH_LIFTING',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '吊运已完成，请查看订单并评价服务。',
  },
  {
    key: 'invoice_issued',
    triggerNode: 'ISSUE_INVOICE',
    recipient: 'user',
    channels: ['wechat_subscribe', 'in_app'],
    content: '服务商已开具发票，可联系服务商获取票据信息。',
  },
  {
    key: 'order_closed',
    triggerNode: 'ORDER_CLOSED',
    recipient: 'user',
    channels: ['wechat_subscribe', 'sms', 'in_app'],
    content: '订单已关闭，原因：{{reason}}。',
  },
  {
    key: 'complaint_resolved',
    triggerNode: 'COMPLAINT_RESOLVED',
    recipient: 'user',
    channels: ['wechat_subscribe', 'in_app'],
    content: '您的投诉已处理，结果：{{result}}。',
  },
]
